import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions",
  description:
    "The terms that govern your use of Expense Tracker, including accounts, acceptable use, and disclaimers.",
};

export default function TermsPage() {
  return (
    <>
      <h1>Terms and Conditions</h1>
      <p>
        <strong>Last updated: June 22, 2026</strong>
      </p>

      <p>
        These Terms and Conditions (&ldquo;Terms&rdquo;) govern your use of{" "}
        <strong>Expense Tracker</strong> (the &ldquo;Service&rdquo;) at{" "}
        <a href="https://expense-tracker.yjaphzs.xyz">
          expense-tracker.yjaphzs.xyz
        </a>
        . By using the Service — or by creating an account — you agree to these
        Terms. If you do not agree, please don&apos;t use the Service.
      </p>

      <h2>1. The Service</h2>
      <p>
        Expense Tracker is a free tool that helps you record income and
        expenses, organize them into wallets and categories, set up recurring
        transactions, and view simple analytics of your own money. It can be
        used without an account; creating one simply lets you save your data and
        sync it across devices.
      </p>

      <h2>2. Not financial advice</h2>
      <p>
        The Service is a personal bookkeeping tool. Any balances, totals,
        charts, or summaries it shows are{" "}
        <strong>calculated solely from the figures you enter</strong> and are
        provided for your personal reference only. They are{" "}
        <strong>not</strong> financial, accounting, tax, or investment advice,
        and may not reflect your actual account balances. You are responsible for
        the accuracy of the data you enter and for any decision you make based on
        it. Any file you export or download from the Service (for example a JSON
        backup or a spreadsheet export) is simply a copy of the data you entered
        — it is not an official financial statement and is not certified by any
        bank or authority.
      </p>

      <h2>3. Accounts</h2>
      <p>
        To create an account you must provide a valid email address (or sign in
        with Google). You are responsible for keeping your credentials secure
        and for all activity under your account. Provide accurate information
        and notify us of any unauthorized use. You must be old enough to form a
        binding agreement in your jurisdiction, or have a parent or
        guardian&apos;s consent.
      </p>

      <h2>4. Your data and content</h2>
      <p>
        You retain ownership of the data you enter (transactions, amounts,
        categories, wallets, recurring items, and profile details). By using the
        Service with an account, you grant us permission to store, process, and
        sync that data solely to operate the Service for you, as described in our{" "}
        <a href="/privacy-policy">Privacy Policy</a>. You are responsible for the
        accuracy of the data you enter.
      </p>

      <h2>5. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose.</li>
        <li>
          Attempt to gain unauthorized access to the Service, other
          users&apos; data, or our underlying infrastructure.
        </li>
        <li>
          Interfere with or disrupt the Service, including probing, scraping, or
          overloading it.
        </li>
        <li>
          Upload malicious content, or images that are unlawful, infringing, or
          inappropriate, as your profile photo.
        </li>
        <li>
          Present any export, backup, or summary generated by the Service as an
          official financial statement or bank-issued record.
        </li>
        <li>
          Reverse engineer or misuse the Service in ways that harm us or other
          users.
        </li>
      </ul>

      <h2>6. Availability and changes</h2>
      <p>
        The Service is provided free of charge on an &ldquo;as is&rdquo; and
        &ldquo;as available&rdquo; basis. We may modify, suspend, or discontinue
        any part of it at any time, and we don&apos;t guarantee uninterrupted or
        error-free operation. We may also update features, including how data is
        stored or synced.
      </p>

      <h2>7. Disclaimers and limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, the Service is provided without
        warranties of any kind, whether express or implied, including fitness
        for a particular purpose and accuracy of results. To the maximum extent
        permitted by law, we will not be liable for any indirect, incidental, or
        consequential damages, or for any loss of data, arising from your use of
        — or inability to use — the Service.
      </p>

      <h2>8. Termination</h2>
      <p>
        You may stop using the Service and delete your account at any time from
        the <strong>Account → Security</strong> page. We may suspend or
        terminate access if you violate these Terms or misuse the Service.
      </p>

      <h2>9. Changes to these Terms</h2>
      <p>
        We may revise these Terms from time to time. Material changes will be
        reflected by updating the &ldquo;Last updated&rdquo; date above.
        Continued use of the Service after changes means you accept the revised
        Terms.
      </p>

      <h2>10. Governing law</h2>
      <p>
        These Terms are governed by the laws of the Republic of the Philippines,
        without regard to its conflict-of-law rules. Any disputes will be
        subject to the exclusive jurisdiction of the competent courts located in
        the Philippines.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these Terms? Email{" "}
        <a href="mailto:jan@yjaphzs.xyz">jan@yjaphzs.xyz</a>.
      </p>
    </>
  );
}
